# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtrash < Formula
  desc "Trash CLI Manager written in Go"
  homepage "https://github.com/umlx5h/gtrash"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umlx5h/gtrash/releases/download/v0.0.1/gtrash_Darwin_x86_64
 # Only include binary.tar.gz"
      sha256 "ada8557b0e6778639c9f0b237c5d9d7b6e2f1a46bab9042e901b2bb9224cae1c"

      def install
        bin.install "gtrash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umlx5h/gtrash/releases/download/v0.0.1/gtrash_Darwin_arm64
 # Only include binary.tar.gz"
      sha256 "375c1b3e0e01c04b0a0c05fe490f0ec31bdde8fe3e86fd0ed9a0e930f1f90444"

      def install
        bin.install "gtrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umlx5h/gtrash/releases/download/v0.0.1/gtrash_Linux_arm64
 # Only include binary.tar.gz"
      sha256 "9184e6c0557ef2869b860c54f8f5b7b7e66c64a7813941a4499dd1fa198f506b"

      def install
        bin.install "gtrash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umlx5h/gtrash/releases/download/v0.0.1/gtrash_Linux_x86_64
 # Only include binary.tar.gz"
      sha256 "749795d71d9a7dcd803ee94d397e86df890e1759a77f69de21c3634acaf8e7e7"

      def install
        bin.install "gtrash"
      end
    end
  end
end
