# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtrash < Formula
  desc "Trash CLI Manager written in Go"
  homepage "https://github.com/umlx5h/gtrash"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/umlx5h/gtrash/releases/download/v0.0.1/gtrash_Darwin_arm64.tar.gz"
      sha256 "baf572f6e96729017b3b9e513c95c2c4dc80c31dfbeaf2c0e77821db68fdf189"

      def install
        bin.install "gtrash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umlx5h/gtrash/releases/download/v0.0.1/gtrash_Darwin_x86_64.tar.gz"
      sha256 "6772218fb05f36063c3d6c5420c72e2fe39b4c4378a0737aff91babcfe3888f5"

      def install
        bin.install "gtrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umlx5h/gtrash/releases/download/v0.0.1/gtrash_Linux_arm64.tar.gz"
      sha256 "eef28f73b665624bd1c9fbf23c0c8ba65346c8f6278c4592c960ed26c06d8b7f"

      def install
        bin.install "gtrash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umlx5h/gtrash/releases/download/v0.0.1/gtrash_Linux_x86_64.tar.gz"
      sha256 "b5f924a8b841efcea9704f37b9b23cf9e04f62e5085c0b27fc8f004fad47f110"

      def install
        bin.install "gtrash"
      end
    end
  end
end
