# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZshManpageCompletionGenerator < Formula
  desc "Automatically generate zsh completions from man page"
  homepage "https://github.com/umlx5h/zsh-manpage-completion-generator"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umlx5h/zsh-manpage-completion-generator/releases/download/v1.0.1/zsh-manpage-completion-generator_Darwin_x86_64.tar.gz"
      sha256 "80e0247cda791593e538a35a12e45718dae7d6120682101bd7b7200cb02154e9"

      def install
        bin.install "zsh-manpage-completion-generator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umlx5h/zsh-manpage-completion-generator/releases/download/v1.0.1/zsh-manpage-completion-generator_Darwin_arm64.tar.gz"
      sha256 "b784fbe41dab7037a1c880d0fae3245cd1d5f75c56c1a9469483bd0ca4c8f291"

      def install
        bin.install "zsh-manpage-completion-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umlx5h/zsh-manpage-completion-generator/releases/download/v1.0.1/zsh-manpage-completion-generator_Linux_arm64.tar.gz"
      sha256 "bf93ffc88ebdc67150834124fc231a5141acc39402a7195b12cc26f5b7d7f666"

      def install
        bin.install "zsh-manpage-completion-generator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umlx5h/zsh-manpage-completion-generator/releases/download/v1.0.1/zsh-manpage-completion-generator_Linux_x86_64.tar.gz"
      sha256 "267427b5e7956c2c20cf4cd4374e3eded530dabfd05ce763026a64586458c4a5"

      def install
        bin.install "zsh-manpage-completion-generator"
      end
    end
  end
end
